import type { Faq } from "@/lib/catalog";

export type ServiceDoc = {
  slug: string | null;
  path: string;
  name: string;
  stype: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  lead: string;
  answer: string;
  incH: string;
  incLead?: string;
  includes: [string, string][];
  howH: string;
  how: [string, string][];
  repH: string;
  report: string[];
  connects: [string, string][];
  faqs: Faq[];
  extra?: "ai";
};

export const SERVICE_DOCS: ServiceDoc[] = [
  {
    slug: null,
    path: "/ai-visibility",
    name: "AI visibility",
    stype: "Generative engine optimization (GEO) for senior living",
    title:
      "AI Visibility for Senior Living: Get Cited by ChatGPT, Gemini & AI Overviews | BrightLeads.AI",
    description:
      "AI visibility (GEO/AEO) for senior living communities. We make assisted living, memory care, and care homes easy for ChatGPT, Gemini, Perplexity, and Google AI Overviews to find, trust, and cite.",
    eyebrow: "AI visibility · GEO · AEO",
    h1: "Show up when families ask AI, not only Google.",
    lead: "Adult children now ask assistants to shortlist communities, compare care types, and explain costs. We make your community the one those assistants can understand, verify, and cite.",
    answer:
      "AI visibility for senior living is the work of making a community easy for AI assistants such as ChatGPT, Gemini, Perplexity, Claude, Copilot, and Google AI Overviews to find, understand, trust, and cite. BrightLeads.AI does it with a consistent entity fact set, schema.org structured data, answer-ready pages, open crawl access including llms.txt, corroborating listings and reviews, and a monthly prompt panel that measures how often each community is mentioned and cited.",
    incH: "Everything it takes to be cited in AI answers.",
    incLead: "Included in every BrightLeads.AI plan. Also available on its own.",
    includes: [
      ["AI visibility audit", "We run your community through a panel of real family questions across major assistants and record who gets named, who gets cited, and what is wrong."],
      ["Entity fact sheet", "One source of truth for every community: names, license numbers, care types, capacity, pricing ranges, amenities, and contact details."],
      ["Schema.org implementation", "Organization, LocalBusiness per location, Service, FAQPage, Review, and BreadcrumbList markup, validated and maintained."],
      ["Answer-ready page program", "Care-type, city, cost, comparison, and FAQ pages written in a question-and-answer structure models can quote."],
      ["Crawl and llms.txt setup", "AI crawler access, llms.txt and llms-full.txt, Markdown alternates, sitemaps, and render checks."],
      ["Corroboration and citations", "Listings, directories, licensing records, reviews, and local mentions aligned so every source agrees."],
    ],
    extra: "ai",
    howH: "From invisible to cited.",
    how: [
      ["Baseline the prompt panel", "We build 40 to 100 real family questions for your markets and care types and record today's answers across assistants."],
      ["Fix entity conflicts", "We find and correct mismatched names, addresses, phone numbers, and care types across your site and the web."],
      ["Ship structure and access", "Schema, robots rules, llms.txt, sitemaps, and fast static rendering go live."],
      ["Publish answer pages", "We write and publish the pages the panel shows are missing, starting with the highest-intent questions."],
      ["Re-measure monthly", "Same panel, same assistants, every month. You see mention rate, citation rate, and accuracy trend by community."],
    ],
    repH: "AI visibility metrics you can track.",
    report: [
      "Mention rate: the share of panel questions where an assistant names your community",
      "Citation rate: the share where it links to or cites your site or profile",
      "Answer accuracy: whether assistants state your care types, location, and details correctly",
      "Share of answer against the nearby communities you compete with",
      "AI referral traffic and inquiries from assistant sources",
      "Crawler activity from AI bots in your server logs",
    ],
    connects: [
      ["/services/senior-living-seo", "AI assistants lean on pages that already rank and load well. SEO is the foundation."],
      ["/services/local-seo", "Your Google Business Profile and listings are the corroboration layer assistants check."],
      ["/services/reputation-management", "Review volume, recency, and replies shape how assistants describe you."],
      ["/services/content-social", "Answer-first content gives models passages worth quoting."],
      ["/services/websites", "Static, fast, accessible pages are the easiest for crawlers to read."],
      ["/services/market-research", "The prompt panel is built from real family research in your markets."],
    ],
    faqs: [
      { q: "What is AI visibility?", a: "AI visibility is how often and how accurately AI assistants mention and cite your community when people ask about senior care. It is also called generative engine optimization (GEO), answer engine optimization (AEO), or AI SEO." },
      { q: "Which AI assistants does this cover?", a: "ChatGPT (including ChatGPT search), Google Gemini, Google AI Overviews and AI Mode, Perplexity, Anthropic Claude, and Microsoft Copilot. We add others as families start using them." },
      { q: "Can you guarantee my community will be recommended by ChatGPT?", a: "No one can guarantee what an AI model says. What we can do is remove the reasons models leave you out, give them accurate facts and quotable pages, and measure the result every month with a consistent prompt panel." },
      { q: "How long does AI visibility take to work?", a: "Fixes to entity data, schema, and crawl access can show up within weeks for assistants that search the live web, such as ChatGPT search, Perplexity, and AI Overviews. Changes that depend on model training take longer. We report monthly so you can see the trend." },
      { q: "Do I still need SEO?", a: "Yes. Assistants that browse the web rely heavily on pages that already rank and load well. AI visibility builds on SEO rather than replacing it, and both are included in our full-service plans." },
      { q: "What is llms.txt?", a: "llms.txt is a plain-text file at the root of a website that gives AI systems a short, structured summary of who you are and links to your most important pages. It is a proposed standard. We publish one for every client site, and you can read ours at /llms.txt." },
    ],
  },
  {
    slug: "senior-living-seo",
    path: "/services/senior-living-seo",
    name: "Senior living SEO",
    stype: "Search engine optimization for senior living",
    title: "Senior Living SEO Agency | Assisted Living & Memory Care SEO | BrightLeads.AI",
    description: "Senior living SEO for assisted living, memory care, independent living, and care homes. Technical SEO, care-type and city pages, and content that ranks and feeds AI answers.",
    eyebrow: "Senior living SEO",
    h1: "SEO that brings families to the right page, for the right care type.",
    lead: "Families search by care type, city, cost, and urgency. We build and optimize the pages that match those searches, then keep them technically healthy and ready to be quoted by AI.",
    answer: "Senior living SEO is the work of ranking a community's website for the searches families run when looking for care, such as memory care near me or assisted living cost in San Mateo. BrightLeads.AI handles technical SEO, care-type and city landing pages, on-page optimization, internal linking, content, and link earning, and builds every page so it can also be cited by AI assistants.",
    incH: "Full-scope SEO for one community or a portfolio.",
    includes: [
      ["Technical SEO", "Crawlability, Core Web Vitals, indexation, redirects, canonical tags, sitemaps, and log review."],
      ["Care-type pages", "Dedicated pages for assisted living, memory care, respite, independent living, and skilled or enhanced care where you offer it."],
      ["City and neighborhood pages", "Useful local pages for the areas families search from, with real local detail instead of swapped city names."],
      ["On-page optimization", "Titles, headings, internal links, images, and schema tuned to search intent."],
      ["Content and FAQs", "Cost guides, comparison pages, and family resources that earn rankings and links."],
      ["Digital PR and links", "Local partnerships, sponsorships, and press that earn links you can be proud of."],
    ],
    howH: "A sequence that compounds.",
    how: [
      ["Audit", "Technical crawl, keyword gap analysis by care type and city, and a competitor review."],
      ["Fix", "Technical and speed issues first, because they limit everything else."],
      ["Map", "Every high-intent search gets a page with one clear job."],
      ["Publish", "New and rewritten pages, each with schema and a short answer at the top."],
      ["Earn", "Links and mentions from local and senior care sources."],
    ],
    repH: "SEO results tied to inquiries.",
    report: ["Organic inquiries, tours, and move-ins by landing page", "Rankings for priority care-type and city terms", "Non-branded organic traffic trend", "Core Web Vitals and indexation health", "New referring domains and local mentions", "AI Overview appearances for tracked queries"],
    connects: [
      ["/ai-visibility", "The same pages, structured to be cited by assistants."],
      ["/services/local-seo", "Organic and map pack rankings reinforce each other."],
      ["/services/websites", "A fast, well-structured site is half of SEO."],
      ["/services/content-social", "Content is how SEO keeps growing."],
      ["/services/paid-media", "Paid search fills gaps while organic rankings build."],
      ["/services/reputation-management", "Reviews affect local rankings and click-through."],
    ],
    faqs: [
      { q: "How long does senior living SEO take?", a: "Technical fixes and local changes often show movement in weeks. Competitive care-type and city rankings usually take three to six months of consistent work. We report progress monthly." },
      { q: "Do you write the content?", a: "Yes. Our writers work from interviews with your team so pages reflect your real care, staff, and neighborhood." },
      { q: "Can you do SEO for multiple communities?", a: "Yes. We build a scalable page and schema structure so every location gets its own care-type pages, local detail, and Google Business Profile alignment." },
    ],
  },
  {
    slug: "local-seo",
    path: "/services/local-seo",
    name: "Local SEO & Google Business Profile",
    stype: "Local search engine optimization",
    title: "Local SEO for Senior Living & Google Business Profile Management | BrightLeads.AI",
    description: "Local SEO for senior living: Google Business Profile optimization, map pack rankings, listings and directory accuracy, and local citations for every community.",
    eyebrow: "Local SEO",
    h1: "Win the map pack for every community you run.",
    lead: "Most senior living searches are local, and many start on a map. We optimize your Google Business Profile, clean up listings everywhere families and models look, and keep them accurate.",
    answer: "Local SEO for senior living is the work of ranking each community in Google's map results and local listings for searches like assisted living near me. BrightLeads.AI optimizes and manages Google Business Profiles, Apple Business Connect and Bing Places listings, senior living directory profiles, and local citations, and keeps name, address, phone, and care-type details consistent so both search engines and AI assistants trust them.",
    incH: "Every local signal, managed.",
    includes: [
      ["Google Business Profile", "Categories, services, attributes, photos, posts, Q&A, and booking links, managed monthly."],
      ["Apple, Bing, and maps", "Apple Business Connect, Bing Places, and major map and navigation listings."],
      ["Directory cleanup", "Consistent profiles on senior living directories, referral sites, and local business listings."],
      ["Duplicate and error fixes", "Merge duplicates, fix wrong addresses and phone numbers, and correct care-type mislabels."],
      ["Local content", "Community events, neighborhood detail, and posts that show real local activity."],
      ["Multi-location management", "One process for every location, with location-level reporting."],
    ],
    howH: "Clean, then compete.",
    how: [
      ["Audit listings", "We find every listing for every community and flag conflicts."],
      ["Correct the facts", "One fact set, pushed everywhere, with duplicates removed."],
      ["Optimize profiles", "Categories, services, photos, and attributes set up to win relevant searches."],
      ["Drive reviews", "A steady flow of new reviews and prompt replies."],
      ["Post and monitor", "Ongoing posts, Q&A, and monitoring for unwanted edits."],
    ],
    repH: "Local metrics by location.",
    report: ["Map pack rank by care type across a local grid", "Calls, direction requests, and website clicks from each profile", "Listing accuracy score across directories", "Review count, rating, and reply rate", "Tours and move-ins from local search"],
    connects: [
      ["/services/reputation-management", "Reviews are the strongest local ranking and conversion signal you control."],
      ["/ai-visibility", "Listings are how assistants corroborate your facts."],
      ["/services/senior-living-seo", "Local pages on your site support map rankings."],
      ["/services/paid-media", "Local search ads cover the top of the map results."],
    ],
    faqs: [
      { q: "Can you manage Google Business Profiles for many locations?", a: "Yes. We manage profiles for single homes and multi-state portfolios with the same process and location-level reporting." },
      { q: "Why do my community's hours or phone number keep changing on Google?", a: "Google accepts suggested edits from users and other sources. We monitor profiles and reverse unwanted changes quickly." },
      { q: "Do you list communities on senior living directories?", a: "Yes. We create and correct profiles on directories and referral sites so the facts match your website. We do not buy fake reviews or listings." },
    ],
  },
  {
    slug: "paid-media",
    path: "/services/paid-media",
    name: "Paid media & PPC",
    stype: "Pay-per-click advertising and media buying",
    title: "Senior Living PPC & Paid Media: Google Ads, Meta & Retargeting | BrightLeads.AI",
    description: "Senior living PPC and paid media management: Google Ads, Performance Max, Meta, YouTube, and retargeting, built for tours and move-ins and compliant with housing ad rules.",
    eyebrow: "Paid media · PPC · Media buying",
    h1: "Ads that turn searches into tours, not just clicks.",
    lead: "We plan, buy, and manage search, social, display, and retargeting campaigns for senior living, and we send every click to a page built for that exact question.",
    answer: "Senior living paid media is advertising on Google, Meta, YouTube, and other platforms to generate inquiries and tours for a community. BrightLeads.AI builds campaigns by care type and location, sends traffic to matching landing pages, tracks calls and forms through to move-ins, and handles housing-related ad rules such as Meta's special ad category. Ad spend runs in accounts you own.",
    incH: "Full-funnel media, managed in your accounts.",
    includes: [
      ["Google search and Performance Max", "Care-type and location campaigns with tight negative keywords and call tracking."],
      ["Meta and Instagram", "Awareness, event, and retargeting campaigns built within housing ad category rules."],
      ["Display and YouTube", "Visual ads for adult children in your trade area, built from your existing photos and video."],
      ["Retargeting", "Stay in front of families during a decision that often takes weeks."],
      ["Landing pages", "Dedicated pages per campaign, tested for conversion."],
      ["Media planning and buying", "Budget allocation across channels and communities based on census need."],
    ],
    howH: "Budget follows census need.",
    how: [
      ["Plan by census", "We weight spend toward communities and care types with open units."],
      ["Build tracking first", "Calls, forms, and chats are tracked through to tours and move-ins."],
      ["Launch matched campaigns", "Every ad group has a landing page that answers its question."],
      ["Optimize weekly", "Search terms, bids, creative, and budgets are tuned every week."],
      ["Report to move-ins", "Cost per inquiry, tour, and move-in by campaign."],
    ],
    repH: "Paid media metrics that matter.",
    report: ["Cost per qualified inquiry, tour, and move-in", "Call recordings and lead quality scoring", "Spend and pacing by community", "Landing page conversion rate", "Impression share on priority care-type searches"],
    connects: [
      ["/services/websites", "Landing pages decide whether an ad click becomes an inquiry."],
      ["/services/crm-automation", "Fast follow-up keeps paid leads from going cold."],
      ["/services/sales-enablement", "Call handling determines cost per move-in more than bids do."],
      ["/services/lease-up", "Paid media carries most pre-opening demand."],
    ],
    faqs: [
      { q: "Do you mark up ad spend?", a: "Ad spend is billed by the platforms directly to your card in your own accounts. Our management fee is separate and flat." },
      { q: "Are senior living ads subject to housing rules?", a: "Often, yes. Meta requires many housing-related ads to run in its special ad category, which limits targeting by age, gender, and ZIP code. We build campaigns that comply and still reach the right families." },
      { q: "What budget do we need?", a: "It depends on your market, care types, and occupancy goals. We recommend a starting budget after the audit and adjust based on cost per move-in." },
    ],
  },
  {
    slug: "websites",
    path: "/services/websites",
    name: "Websites & conversion",
    stype: "Website design and development for senior living",
    title: "Senior Living Website Design & Development | BrightLeads.AI",
    description: "Senior living website design: fast, accessible, mobile-first community websites written for adult children, built to convert inquiries, and structured for SEO and AI visibility.",
    eyebrow: "Websites · Conversion rate optimization",
    h1: "A community website families can actually inquire from.",
    lead: "Most senior living sites look fine and convert poorly. We design and build sites around the questions families ask and the fastest path to a tour.",
    answer: "A senior living website is the main place families and AI assistants learn about a community. BrightLeads.AI designs and builds fast, accessible, mobile-first sites with care-type pages, pricing guidance, virtual tours, clear calls to action, and structured data, and runs conversion testing so more visitors become inquiries and tours.",
    incH: "Design, build, and ongoing improvement.",
    includes: [
      ["Strategy and sitemap", "A page for every care type, location, and high-intent question."],
      ["Design", "Clean, warm, readable design with large type and high contrast for older readers."],
      ["Development", "Fast static or headless builds, or WordPress when your team needs it."],
      ["Accessibility", "Built to WCAG 2.2 AA, tested with keyboard and screen readers."],
      ["Conversion tools", "Tour scheduling, click-to-call, pricing request, chat, and short forms."],
      ["Testing and CRO", "Ongoing A/B tests on headlines, forms, and calls to action."],
    ],
    howH: "Built to be read by families and machines.",
    how: [
      ["Discover", "Interviews with your sales team and a review of inquiry data."],
      ["Architect", "Sitemap and page templates mapped to search and AI questions."],
      ["Write", "Copy that sounds like your community, with an answer at the top of every page."],
      ["Build", "Performance, schema, accessibility, and tracking are part of the build."],
      ["Improve", "Monthly testing and new pages based on what families ask."],
    ],
    repH: "Website metrics we improve.",
    report: ["Visitor-to-inquiry conversion rate by page and device", "Tour requests and calls from the site", "Core Web Vitals and page speed", "Accessibility audit results", "Form abandonment and drop-off points"],
    connects: [
      ["/ai-visibility", "Your site is the primary source assistants cite."],
      ["/services/senior-living-seo", "Structure and speed drive rankings."],
      ["/services/crm-automation", "Every form routes straight into your CRM."],
      ["/services/branding", "The site carries your brand to families first."],
    ],
    faqs: [
      { q: "Do we own the website?", a: "Yes. The domain, code, content, and hosting account are yours." },
      { q: "Which platform do you build on?", a: "We recommend fast static or headless builds for performance and AI crawlability, and we also build on WordPress when your team needs to edit pages often." },
      { q: "Can you redesign without losing our search rankings?", a: "Yes. We map every existing URL, set redirects, and carry over content that performs before launch." },
    ],
  },
  {
    slug: "reputation-management",
    path: "/services/reputation-management",
    name: "Reputation & PR",
    stype: "Online reputation management and public relations",
    title: "Senior Living Reputation Management, Reviews & PR | BrightLeads.AI",
    description: "Reputation management for senior living: ethical review generation, review response, monitoring, crisis support, and local public relations that build trust with families and AI.",
    eyebrow: "Reputation · Reviews · PR",
    h1: "Build the reputation families and AI assistants check first.",
    lead: "Reviews shape local rankings, click-through, and what AI assistants say about you. We grow authentic reviews, respond to every one, and earn local attention.",
    answer: "Reputation management for senior living is the work of growing authentic reviews, responding to them, monitoring what is said about a community, and earning positive media coverage. BrightLeads.AI runs ethical review requests from families and residents, drafts replies that protect resident privacy, monitors Google and senior living directories, and handles local public relations.",
    incH: "Reviews, response, and earned media.",
    includes: [
      ["Review generation", "Timed, compliant review requests to families and residents at the right moments."],
      ["Review response", "Replies drafted for every review, written to avoid disclosing resident health information."],
      ["Monitoring", "Alerts across Google, Facebook, Yelp, and senior living directories."],
      ["Crisis support", "Response plans for negative press, survey findings, or viral complaints."],
      ["Local PR", "Story pitching, events, and community partnerships that earn coverage."],
      ["Awards and recognition", "Help applying for legitimate industry and local recognition."],
    ],
    howH: "Authentic, steady, and responsive.",
    how: [
      ["Audit reputation", "Ratings, volume, recency, and themes across every platform."],
      ["Set up requests", "Automated, compliant review requests from your CRM."],
      ["Respond to everything", "Positive and negative reviews answered promptly."],
      ["Pitch stories", "Local media and partner outlets."],
      ["Report themes", "What families praise and complain about, shared with operations."],
    ],
    repH: "Reputation metrics.",
    report: ["Average rating and review count by platform and community", "Review velocity and recency", "Response rate and response time", "Sentiment themes for operations", "Media mentions and earned links"],
    connects: [
      ["/services/local-seo", "Reviews drive map pack rankings."],
      ["/ai-visibility", "Assistants summarize review themes in their answers."],
      ["/services/crm-automation", "Review requests trigger from CRM milestones."],
      ["/services/content-social", "Positive stories become content."],
    ],
    faqs: [
      { q: "Do you write fake reviews?", a: "Never. Fake reviews violate platform rules and FTC rules, and they erode trust. We help you ask real residents and families at the right time." },
      { q: "How do you respond to reviews without violating privacy?", a: "Replies never confirm that someone is a resident or mention health details. We use approved templates and route sensitive reviews to your team." },
      { q: "Can you remove negative reviews?", a: "We can flag reviews that violate platform policies for removal. For legitimate negative reviews, a thoughtful public reply and an operational fix work better." },
    ],
  },
  {
    slug: "branding",
    path: "/services/branding",
    name: "Branding & creative",
    stype: "Brand strategy and creative services",
    title: "Senior Living Branding, Naming & Creative | BrightLeads.AI",
    description: "Senior living branding: positioning, naming, visual identity, brand voice, photography direction, and storytelling that sets your community apart in its market.",
    eyebrow: "Branding · Creative · Storytelling",
    h1: "A brand that makes your community easy to choose.",
    lead: "In a market full of similar promises, a clear position and a warm, specific story are what families remember. We build brands grounded in what actually makes your community different.",
    answer: "Senior living branding is the work of defining what makes a community different and expressing it consistently in name, identity, voice, photography, and story. BrightLeads.AI provides positioning research, naming, logo and visual identity, brand voice guidelines, photography guidance, and campaign creative, and writes brand facts so AI assistants describe the community the same way.",
    incH: "From positioning to every touchpoint.",
    includes: [
      ["Positioning", "Research with residents, families, and staff to find your real point of difference."],
      ["Naming", "Community and neighborhood naming, checked for conflicts."],
      ["Visual identity", "Logo, color, type, and layout systems built for readability."],
      ["Brand voice", "Guidelines so sales, marketing, and staff sound consistent."],
      ["Photography guidance", "Direction on the real photos of residents, staff, and spaces that tell your story."],
      ["Campaign creative", "Ads, print, signage, and collateral."],
    ],
    howH: "Research first, then design.",
    how: [
      ["Listen", "Interviews with residents, families, staff, and referral partners."],
      ["Position", "A short, defensible positioning statement and proof points."],
      ["Express", "Name, identity, and voice."],
      ["Apply", "Website, signage, sales materials, and ads."],
      ["Govern", "Guidelines and templates so the brand stays consistent."],
    ],
    repH: "How we measure brand work.",
    report: ["Branded search volume over time", "Direct and referral traffic trends", "Tour-to-move-in conversion with new materials", "Consistency of brand facts across listings and AI answers"],
    connects: [
      ["/services/websites", "The website is where the brand is experienced first."],
      ["/services/content-social", "Story drives content and social."],
      ["/services/lease-up", "New communities need a brand before they need ads."],
      ["/services/market-research", "Positioning starts with research."],
    ],
    faqs: [
      { q: "Do we need a rebrand?", a: "Not always. Many communities need sharper positioning and better photography rather than a new logo. The audit tells us which." },
      { q: "Can you brand a portfolio of communities?", a: "Yes. We build parent and community brand architecture so each location has its own identity within a family." },
    ],
  },
  {
    slug: "content-social",
    path: "/services/content-social",
    name: "Content & social",
    stype: "Content marketing and social media",
    title: "Senior Living Content Marketing & Social Media | BrightLeads.AI",
    description: "Senior living content marketing: answer-first articles, cost and care guides, resident stories, email content, and social media that feeds SEO, AI answers, and nurture.",
    eyebrow: "Content · Social · Email",
    h1: "Content that answers families, and gets quoted by AI.",
    lead: "Families research for weeks before they call. We create the guides, stories, and posts that help them decide, and we write them so search engines and AI assistants can use them.",
    answer: "Senior living content marketing creates the articles, guides, stories, and social posts families use while researching care. BrightLeads.AI produces answer-first content on costs, care levels, and decisions, resident and staff stories, and social media, and uses each piece across search, AI answers, email nurture, and sales follow-up.",
    incH: "One content engine, many channels.",
    includes: [
      ["Answer-first articles", "Guides that open with a direct answer, then go deep."],
      ["Cost and care guides", "Clear explanations of pricing, care levels, and payment options."],
      ["Resident and staff stories", "Written profiles and photo stories, with consent, that show real life in your community."],
      ["Social media", "Organic posting and community management on the platforms your families use."],
      ["Email content", "Newsletters and nurture sequences for prospects and referral partners."],
      ["Sales collateral", "Follow-up pieces that answer the questions asked on tours."],
    ],
    howH: "Plan from real questions.",
    how: [
      ["Collect questions", "From your sales team, call recordings, search data, and AI prompt panels."],
      ["Prioritize", "Highest-intent and least-answered questions first."],
      ["Produce", "Written and designed with your team."],
      ["Distribute", "Site, social, email, and sales follow-up."],
      ["Refresh", "Update pages as prices, services, and questions change."],
    ],
    repH: "Content metrics.",
    report: ["Inquiries influenced by content", "Organic traffic and rankings for content pages", "Citations of content in AI answers", "Email engagement and reply rates", "Social reach and engagement by community"],
    connects: [
      ["/ai-visibility", "Quotable passages are what assistants cite."],
      ["/services/senior-living-seo", "Content earns rankings and links."],
      ["/services/crm-automation", "Content fuels nurture sequences."],
      ["/services/sales-enablement", "Sales uses content to follow up after tours."],
    ],
    faqs: [
      { q: "How often should a senior living community publish?", a: "Consistency matters more than volume. Most communities do well with two to four strong pieces a month, plus regular updates to core pages." },
      { q: "Do you produce video?", a: "No. We do not film on site. If you already have video, we can use it in content, social, and ads." },
    ],
  },
  {
    slug: "crm-automation",
    path: "/services/crm-automation",
    name: "CRM & lead nurturing",
    stype: "CRM integration and marketing automation",
    title: "Senior Living CRM Integration & Lead Nurturing Automation | BrightLeads.AI",
    description: "Senior living CRM and marketing automation: lead routing, lead scoring, email and SMS nurture, and reporting in HubSpot, Salesforce, GoHighLevel, or your senior-living CRM.",
    eyebrow: "CRM · Automation · Lead nurturing",
    h1: "No inquiry left in an inbox nobody checks.",
    lead: "Senior living decisions take weeks or months. We connect every lead source to your CRM, route leads instantly, and nurture families until they are ready to tour.",
    answer: "Senior living CRM and marketing automation connects every inquiry source to one system, routes leads to the right person immediately, scores them, and nurtures families with timely email and text until they are ready to tour or move in. BrightLeads.AI builds this in HubSpot, Salesforce, GoHighLevel, or the senior-living CRM your team already uses, with texting set up for TCPA and A2P 10DLC compliance.",
    incH: "The plumbing that keeps leads alive.",
    includes: [
      ["Lead capture and routing", "Forms, calls, chats, and referral sources flow into the CRM and reach the right person in seconds."],
      ["CRM setup or cleanup", "Pipelines, stages, fields, and deduplication that match how your sales team works."],
      ["Lead scoring", "Scores based on care need, timeline, and engagement so sales calls the right families first."],
      ["Email and SMS nurture", "Sequences by care type and stage, with compliant opt-in and 10DLC registration."],
      ["Referral partner tracking", "Track placement agents, hospitals, and professional referrers as sources."],
      ["Attribution and dashboards", "Source-to-move-in reporting that marketing and operations both trust."],
    ],
    howH: "Map the journey, then automate it.",
    how: [
      ["Map your process", "From first inquiry to move-in, including every handoff."],
      ["Clean the data", "Deduplicate, standardize sources, and fix stages."],
      ["Connect the sources", "Website, ads, calls, chat, and referral partners."],
      ["Automate follow-up", "Alerts, tasks, and nurture sequences."],
      ["Report", "Dashboards by source, community, and salesperson."],
    ],
    repH: "Pipeline metrics.",
    report: ["Speed to lead: time from inquiry to first contact", "Inquiry-to-tour and tour-to-move-in rates by source", "Nurture engagement and re-activated leads", "Pipeline value by stage and community", "Lead source attribution through to move-in"],
    connects: [
      ["/services/sales-enablement", "Automation supports the people who close."],
      ["/services/paid-media", "Paid leads are expensive to waste."],
      ["/services/reputation-management", "Review requests trigger from CRM milestones."],
      ["/services/content-social", "Nurture needs good content."],
    ],
    faqs: [
      { q: "Which CRMs do you work with?", a: "HubSpot, Salesforce, GoHighLevel, and the common senior-living CRMs. If you already have a CRM, we usually improve it rather than replace it." },
      { q: "Is texting families legal?", a: "Yes, with prior consent and proper registration. We set up opt-in language, A2P 10DLC registration, and quiet hours so your texting complies with the TCPA and carrier rules." },
      { q: "Can you integrate referral partners like placement agencies?", a: "Yes. We track referral sources so you can see which partners send families who move in." },
    ],
  },
  {
    slug: "sales-enablement",
    path: "/services/sales-enablement",
    name: "Sales enablement",
    stype: "Senior living sales consulting and training",
    title: "Senior Living Sales Enablement & Training | BrightLeads.AI",
    description: "Senior living sales enablement: speed-to-lead, inquiry call scripts, tour playbooks, follow-up cadences, call review, and sales coaching that turn inquiries into move-ins.",
    eyebrow: "Sales enablement · Training",
    h1: "Turn more inquiries into tours, and more tours into move-ins.",
    lead: "Marketing creates inquiries. Sales creates move-ins. We help your team respond faster, ask better questions, run memorable tours, and follow up until the family decides.",
    answer: "Senior living sales enablement gives a community's sales team the process, tools, and coaching to convert inquiries into tours and move-ins. BrightLeads.AI provides speed-to-lead systems, discovery call guides, tour playbooks, follow-up cadences, call review, and coaching, and connects them to CRM data so results are measurable.",
    incH: "Process, tools, and coaching.",
    includes: [
      ["Speed-to-lead setup", "Alerts, routing, and backup rules so every inquiry gets a fast response."],
      ["Discovery call guides", "Questions that uncover care needs, timing, and who decides."],
      ["Tour playbooks", "Tours personalized to what the family told you."],
      ["Follow-up cadences", "What to send and when, after the call and after the tour."],
      ["Call review and coaching", "Recorded call reviews and practical feedback."],
      ["Sales reporting", "Activity and conversion by salesperson and community."],
    ],
    howH: "Measure, then coach.",
    how: [
      ["Review the funnel", "Call recordings, CRM data, and response times."],
      ["Find the gaps", "Response time, discovery, tour, and follow-up."],
      ["Equip the team", "Guides, templates, and CRM tasks."],
      ["Coach", "Regular call reviews and role play."],
      ["Track", "Conversion trends by person and source."],
    ],
    repH: "Sales metrics.",
    report: ["Speed to lead and answer rate", "Inquiry-to-tour and tour-to-move-in conversion", "Follow-up completion rate", "Call review scores over time", "Average days from inquiry to move-in"],
    connects: [
      ["/services/crm-automation", "CRM tasks make the playbook stick."],
      ["/services/content-social", "Follow-up content answers tour questions."],
      ["/services/paid-media", "Better conversion lowers cost per move-in."],
      ["/services/market-research", "Know what competitors say on their tours."],
    ],
    faqs: [
      { q: "Do you replace our sales team?", a: "No. We support your team with process, tools, and coaching. Your people build the relationships." },
      { q: "What is speed to lead?", a: "It is the time between a family's inquiry and your first real contact. Families often contact several communities at once, so faster responses tend to win more tours." },
    ],
  },
  {
    slug: "market-research",
    path: "/services/market-research",
    name: "Market research & data",
    stype: "Senior living market research and data services",
    title: "Senior Living Market Research & Competitor Analysis | BrightLeads.AI",
    description: "Senior living market research: market and competitor studies, pricing surveys, audience research, and AI answer audits that turn into a prioritized marketing plan.",
    eyebrow: "Research · Data · Strategy",
    h1: "Know your market before you spend a dollar in it.",
    lead: "Good marketing starts with knowing who you serve, who you compete with, and what families in your market are asking. We do the research and turn it into plans.",
    answer: "Senior living market research studies a community's trade area, competitors, pricing, and prospective residents and families to guide marketing and sales. BrightLeads.AI provides market and competitor studies, pricing surveys, family and resident interviews, and AI answer audits, and turns the findings into a prioritized plan.",
    incH: "Research that becomes a plan.",
    includes: [
      ["Market study", "Trade area demographics, supply, and demand by care type."],
      ["Competitor audit", "Websites, pricing, reviews, ads, and AI answer share for nearby communities."],
      ["Pricing survey", "Current rates and fees across your competitive set."],
      ["Audience research", "Interviews and surveys with residents, adult children, and referral partners."],
      ["AI answer audit", "How assistants describe you and your competitors today."],
      ["Prioritized plan", "A marketing plan and budget built from the findings, by community and care type."],
    ],
    howH: "From data to decisions.",
    how: [
      ["Define the question", "Occupancy, pricing, repositioning, or expansion."],
      ["Gather data", "Public data, shops, interviews, and surveys."],
      ["Analyze", "Gaps, threats, and opportunities by care type."],
      ["Recommend", "A prioritized plan with budgets."],
      ["Activate", "Campaigns built from the findings."],
    ],
    repH: "Research deliverables.",
    report: ["Written findings with a prioritized plan", "Competitor comparison tables", "Pricing position by care type", "Target audience profiles", "Baseline metrics to measure progress against"],
    connects: [
      ["/services/branding", "Positioning comes from research."],
      ["/services/lease-up", "New developments need market validation."],
      ["/ai-visibility", "The AI answer audit is the baseline."],
      ["/services/paid-media", "Research shapes targeting and budget."],
    ],
    faqs: [
      { q: "Do we need research before marketing?", a: "Not always. Established communities with good data can start with a competitor and AI answer audit. New developments, repositioning, and expansion decisions benefit from a full market study." },
      { q: "Do you provide direct mail or mailing lists?", a: "No. We focus on digital channels, sales process, and AI visibility." },
    ],
  },
  {
    slug: "lease-up",
    path: "/services/lease-up",
    name: "Lease-up & repositioning",
    stype: "Senior living lease-up and occupancy recovery marketing",
    title: "Senior Living Lease-Up Marketing & Occupancy Recovery | BrightLeads.AI",
    description: "Lease-up marketing for new senior living communities and occupancy recovery for struggling ones: pre-opening demand, deposit programs, events, paid media, and weekly pacing.",
    eyebrow: "Lease-up · Repositioning · Occupancy recovery",
    h1: "Open full, or get back to full.",
    lead: "New communities need a waiting list before they open. Struggling communities need a reset. We run focused programs for both, with weekly pacing against your targets.",
    answer: "Senior living lease-up marketing builds demand for a new community before and after opening, with brand launch, a pre-opening website, priority deposit programs, events, paid media, and a sales process tracked weekly against occupancy targets. BrightLeads.AI also runs repositioning programs for existing communities that need to recover occupancy after a change in ownership, care offering, or reputation.",
    incH: "A program with a target and a timeline.",
    includes: [
      ["Pre-opening brand and site", "A brand, a website, and a sales office presence well before opening."],
      ["Priority list and deposits", "Programs that turn interest into commitment."],
      ["Events", "Hard-hat tours, information sessions, and community partnerships."],
      ["Paid media launch", "Search, social, and display aimed at your trade area."],
      ["Sales support", "Pipeline management and weekly pacing reviews."],
      ["Repositioning", "Research, message, and channel reset for communities that need a turnaround."],
    ],
    howH: "Paced to your occupancy target.",
    how: [
      ["Validate demand", "Market study and pricing check."],
      ["Launch the brand", "Name, identity, site, and first campaigns."],
      ["Build the list", "Leads, events, and deposit program."],
      ["Convert", "Tours, move-in scheduling, and follow-up."],
      ["Pace weekly", "Progress against the lease-up curve, with adjustments."],
    ],
    repH: "Lease-up tracking.",
    report: ["Deposits and move-ins against the lease-up plan", "Lead volume and cost by channel", "Event attendance and conversion", "Pipeline by care type and unit type", "Weekly pacing reports"],
    connects: [
      ["/services/market-research", "Validate demand and pricing first."],
      ["/services/branding", "A new community needs a brand."],
      ["/services/paid-media", "Paid media drives early demand."],
      ["/services/sales-enablement", "Lease-up sales need a tight process."],
    ],
    faqs: [
      { q: "When should lease-up marketing start?", a: "Ideally 12 to 18 months before opening for larger communities, and at least six months ahead for smaller ones." },
      { q: "Can you help a community that has lost occupancy?", a: "Yes. We start with research on why, then reset positioning, reputation, channels, and sales process." },
    ],
  },
];

export function serviceBySlug(slug: string) {
  return SERVICE_DOCS.find((s) => s.slug === slug);
}

export function serviceByPath(path: string) {
  return SERVICE_DOCS.find((s) => s.path === path);
}
